version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo-server
    environment:
      MONGO_INITDB_ROOT_USERNAME: partho
      MONGO_INITDB_ROOT_PASSWORD: partho
    ports:
      - "27017:27017"

  graphql:
    build: .
    container_name: graphql-server
    environment:
      - MONGO_URI=mongodb://partho:partho@mongo-server:27017/mydb?authSource=admin
    ports:
      - "3010:3000"
    depends_on:
      - mongo
